UPDATE `Event`
SET
    `Title` = CASE `Event_id`
        WHEN 4 THEN 'Will the U.S. enter a recession by December 31, 2026?'
        WHEN 5 THEN 'Will Ethereum trade above $7,500 by December 31, 2026?'
        WHEN 6 THEN 'Will Stripe file publicly for an IPO by December 31, 2026?'
        WHEN 7 THEN 'Will a Democrat win the California governor election by November 3, 2026?'
        WHEN 8 THEN 'Will the Federal Reserve cut rates at least once by September 30, 2026?'
        WHEN 9 THEN 'Will the Oklahoma City Thunder win the 2026 NBA Finals by September 19, 2026?'
        WHEN 10 THEN 'Will Solana trade above $400 by October 21, 2026?'
        WHEN 11 THEN 'Will Blue Origin launch New Glenn twice by November 23, 2026?'
        WHEN 12 THEN 'Will OpenAI be valued above $200 billion in a funding round by December 25, 2026?'
        WHEN 13 THEN 'Will Avatar: Fire and Ash gross over $1 billion worldwide by January 27, 2026?'
        WHEN 14 THEN 'Will the U.S. Senate confirm a Supreme Court nominee by February 1, 2026?'
        WHEN 15 THEN 'Will Bitcoin trade above $150,000 by March 3, 2026?'
        WHEN 16 THEN 'Will Intuitive Machines complete another Moon landing by April 5, 2026?'
        WHEN 17 THEN 'Will Klarna complete a U.S. IPO by May 7, 2026?'
        WHEN 18 THEN 'Will Databricks file publicly for an IPO by June 9, 2026?'
        WHEN 19 THEN 'Will the U.S. Senate pass a federal stablecoin bill by July 11, 2026?'
        WHEN 20 THEN 'Will the Florida Panthers win the 2026 Stanley Cup by August 13, 2026?'
        WHEN 21 THEN 'Will NASA launch Artemis II by September 15, 2026?'
        WHEN 22 THEN 'Will The Last of Us win Outstanding Drama Series at the 2026 Emmys by October 17, 2026?'
        WHEN 23 THEN 'Will Anthropic raise more than $5 billion in new funding by November 19, 2026?'
        WHEN 24 THEN 'Will Congress pass a federal budget deal by December 21, 2026?'
        WHEN 25 THEN 'Will XRP trade above $5 by January 23, 2026?'
        WHEN 26 THEN 'Will SpaceX complete an on-orbit refueling demo with Starship by February 25, 2026?'
        WHEN 27 THEN 'Will Circle complete an IPO by March 27, 2026?'
        WHEN 28 THEN 'Will Discord announce a sale or IPO plan by April 1, 2026?'
        WHEN 29 THEN 'Will the U.S. House pass a national crypto market structure bill by May 3, 2026?'
        WHEN 30 THEN 'Will Real Madrid win the 2026 UEFA Champions League by June 5, 2026?'
        WHEN 31 THEN 'Will Rocket Lab launch Neutron by July 7, 2026?'
        WHEN 32 THEN 'Will Figma complete an IPO by August 9, 2026?'
        WHEN 33 THEN 'Will xAI raise a new funding round above $10 billion by September 11, 2026?'
        WHEN 34 THEN 'Will the U.S. and China hold a formal leaders summit by October 13, 2026?'
        WHEN 35 THEN 'Will Dogecoin trade above $1.00 by November 15, 2026?'
        WHEN 36 THEN 'Will the Kansas City Chiefs clinch an NFL playoff berth by December 17, 2026?'
        WHEN 37 THEN 'Will Germany approve defense spending above 2.5% of GDP by January 19, 2026?'
        WHEN 38 THEN 'Will Netflix premiere the final season of Stranger Things by February 21, 2026?'
        WHEN 39 THEN 'Will the European Union renew major sanctions on Russia by March 23, 2026?'
        WHEN 40 THEN 'Will Ethereum trade above $10,000 by April 25, 2026?'
        WHEN 41 THEN 'Will Vast launch its first commercial space station module by May 27, 2026?'
        WHEN 42 THEN 'Will OpenAI announce an acquisition worth over $1 billion by June 1, 2026?'
        WHEN 43 THEN 'Will a 2026 Marvel film open above $150 million domestically by July 3, 2026?'
        WHEN 44 THEN 'Will Team USA win the 2026 World Baseball Classic by August 5, 2026?'
        WHEN 45 THEN 'Will BNB trade above $1,200 by September 7, 2026?'
        WHEN 46 THEN 'Will Commonwealth Fusion Systems achieve grid-relevant fusion power output by October 9, 2026?'
        WHEN 47 THEN 'Will ByteDance sell TikTok''s U.S. operations by November 11, 2026?'
        WHEN 48 THEN 'Will a Nintendo game win Game of the Year at The Game Awards 2026 by December 13, 2026?'
        WHEN 49 THEN 'Will the U.S. House elect a new Speaker by January 15, 2026?'
        WHEN 50 THEN 'Will a U.S. spot Solana ETF begin trading by February 17, 2026?'
        ELSE `Title`
    END,
    `Category` = CASE `Event_id`
        WHEN 4 THEN 'finance'
        WHEN 5 THEN 'crypto'
        WHEN 6 THEN 'finance'
        WHEN 7 THEN 'politics'
        WHEN 8 THEN 'finance'
        WHEN 9 THEN 'sports'
        WHEN 10 THEN 'crypto'
        WHEN 11 THEN 'science'
        WHEN 12 THEN 'finance'
        WHEN 13 THEN 'entertainment'
        WHEN 14 THEN 'politics'
        WHEN 15 THEN 'crypto'
        WHEN 16 THEN 'science'
        WHEN 17 THEN 'finance'
        WHEN 18 THEN 'finance'
        WHEN 19 THEN 'politics'
        WHEN 20 THEN 'sports'
        WHEN 21 THEN 'science'
        WHEN 22 THEN 'entertainment'
        WHEN 23 THEN 'finance'
        WHEN 24 THEN 'politics'
        WHEN 25 THEN 'crypto'
        WHEN 26 THEN 'science'
        WHEN 27 THEN 'finance'
        WHEN 28 THEN 'finance'
        WHEN 29 THEN 'politics'
        WHEN 30 THEN 'sports'
        WHEN 31 THEN 'science'
        WHEN 32 THEN 'finance'
        WHEN 33 THEN 'finance'
        WHEN 34 THEN 'politics'
        WHEN 35 THEN 'crypto'
        WHEN 36 THEN 'sports'
        WHEN 37 THEN 'politics'
        WHEN 38 THEN 'entertainment'
        WHEN 39 THEN 'politics'
        WHEN 40 THEN 'crypto'
        WHEN 41 THEN 'science'
        WHEN 42 THEN 'finance'
        WHEN 43 THEN 'entertainment'
        WHEN 44 THEN 'sports'
        WHEN 45 THEN 'crypto'
        WHEN 46 THEN 'science'
        WHEN 47 THEN 'finance'
        WHEN 48 THEN 'entertainment'
        WHEN 49 THEN 'politics'
        WHEN 50 THEN 'crypto'
        ELSE `Category`
    END
WHERE `Event_id` BETWEEN 4 AND 50;
